
Look at data + labels
```{r}
require('MetaIntegrator')
gse <- getGEOData("GSE24187") # primary hepatocytes + rifampicin, rosuvastatin, and atorvastatin
expData <- gse$originalData$GSE24187$expr
View(gse$originalData$GSE24187$pheno)

# get the sex labels for each donor
donor_geo <- gse$originalData$GSE24187$pheno[,c("geo_accession", "donor:ch1", "characteristics_ch1.2", "characteristics_ch1.3")]
donor_geo <- rename(donor_geo, "gsm"="geo_accession")
label_donor <- inner_join(donor_geo, comb_w_labels[,c("gsm", "drug_name", "rank_sex", "toker_sex", "massir_sex")])


# make sure these are consistent - they are
split(label_donor, label_donor$`donor:ch1`) # TODO- make this a programmatic check!

donor_sex <- unique(label_donor[,c("donor:ch1", "rank_sex")])

donor_data <- left_join(donor_geo, donor_sex)

# clean up the data
pheno_reform <- donor_data %>% rename("subj"="donor:ch1", "drug"="characteristics_ch1.2", "time"="characteristics_ch1.3", "sex"="rank_sex") 
pheno_reform$drug <- sapply(pheno_reform$drug, function(x) strsplit(tolower(x), ": ")[[1]][[2]]) # remove prefix
pheno_reform$time <- sapply(pheno_reform$time, function(x) gsub("h", "", strsplit(tolower(x), ": ")[[1]][[2]])) # remove hr symbol + prefix

```

comparisons:

```{r}
require('limma')
ato <- filter( pheno_reform, drug %in% c("atorvastatin", "untreated"))
ato48 <- filter(ato, time %in% c(0, 48))
treatments <- factor(c(1,1,2,2,2,1,3,3,4,4,4,3), labels=c("f48", "m48", "f0", "m0"))
contrasts(treatments) <- cbind(Drug=c(1,1,0,0), Sex=c(0,1,0,1))
design <- model.matrix(~treatments)


# Perform linear model fitting 

# want to switch to maanova!!
fit <- lmFit(expData[,c(ato48$gsm)], design)
cont.matrix <- cbind(Drug=c(1,1,0,0), Sex=c(0,1,0,1))
fit.contrast <- contrasts.fit(fit, cont.matrix)
fit.eBayes <- eBayes(fit.contrast)
results.fit.eBayes <- topTable(fit.eBayes, number = Inf)
topTable(fit.eBayes, number = Inf)
decideTests(fit.eBayes, method="nestedF")

```



