---
title: "MappingTables"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
require('tidyverse')
require('biomaRt')
require('mygene')
```


Connect to biomaRt and generate the tables
```{r}
ensembl_h <- useMart("ensembl", dataset="hsapiens_gene_ensembl") 
listAttributes(ensembl_h) %>% dplyr::select(name) %>% filter(str_detect(name, "uni"))
human.dat.map <- getBM(attributes= c("ensembl_gene_id", "hgnc_symbol", "refseq_mrna", "entrezgene_id", "chromosome_name"), mart=ensembl_h) 
dat.map <- human.dat.map
save(dat.map, file="../../data/human_gene_map.RData")


ensembl_m <- useMart("ensembl", dataset="mmusculus_gene_ensembl") 
mouse.dat.map <- getBM(attributes= c("ensembl_gene_id", "hgnc_symbol", "refseq_mrna", "entrezgene_id", "chromosome_name"), mart=ensembl_m) 
dat.map <- mouse.dat.map

save(dat.map, file="../../data/mouse_gene_map.RData")


ensembl_r <- useMart("ensembl", dataset="rnorvegicus_gene_ensembl") 
rat.dat.map <- getBM(attributes= c("ensembl_gene_id", "refseq_mrna", "entrezgene_id", "chromosome_name"), mart=ensembl_r) 
dat.map <- rat.dat.map
save(dat.map, file="../../data/rat_gene_map.RData")

extract_entrez <- function(organism){
   load(sprintf("../../data/%s_gene_map.RData", organism))
  entrez_df <- dat.map %>% filter(entrezgene_id != "") %>% select(entrezgene_id) %>% unique()
  entrezids <- sapply(entrez_df$entrezgene_id, as.character)
  save(entrezids, file=sprintf("../../data/%s_entrezids.RData", organism))
}


extract_entrez("human")
extract_entrez("rat")
extract_entrez("mouse")

```


```{r}

get_unigene <- function(organism){
    require('mygene')

  load(sprintf("../../data/%s_entrezids.RData", organism))
df_unigene <- queryMany(head(entrezids, 50), scopes = "entrezgene", fields = "unigene", species = organism, returnall = TRUE)
unigene <- data.frame(df_unigene$response) %>% 
  dplyr::select("query", "unigene") %>% 
  rename(entrezgene_id=query)

table(sapply(df_unigene$response[,"unigene"], is.null)) # 931 
df_unigene$response$unigene <- sapply(df_unigene$response$unigene, function(x) paste(x, collapse=";"))
my_df <- df_unigene$response[df_unigene$response$unigene!="",]
unigene <- data.frame(my_df) %>% dplyr::select("query", "unigene") %>% 
  rename(entrezgene_id=query) %>% separate_rows(unigene, sep=";")
print(head(unigene))
save(unigene,
     file=sprintf("../../data/%s_unigene.RData", organism ))
}
get_unigene("human")
get_unigene("rat")
get_unigene("mouse")
```


Get X and Y genes in mice